name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Vale
      uses: errata-ai/vale-action@master
      with:
        files: articles/.
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  deploy:
    needs: [prose]

    runs-on: ubuntu-latest

    if: (github.event_name == 'push')

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # See https://github.com/actions/checkout/issues/165#issuecomment-657673315
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1

      - name: Git LFS Pull
        run: git lfs pull

      # Disable environmental variable for this step to disable deterministic builds
      - name: docfx-action
        uses: nikeee/docfx-action@master
        with:
          args: docfx.json
        env:
            GITHUB_ACTIONS : false
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
        env:
            GITHUB_ACTIONS : true
          