name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Vale
      uses: errata-ai/vale-action@master
      with:
        files: articles/.
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  deploy:
    needs: [prose]

    runs-on: ubuntu-latest

    if: (github.event_name == 'push')

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: docfx-action
        uses: nikeee/docfx-action@master
        with:
          args: docfx.json
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs