name: Documentation Checks

on:
  push:
    branches:
      - main #or main if that's what the project is using
  pull_request:
    branches:
      - main
jobs:
  spellcheck:
    name: "Docs: Spellcheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - uses: actions/setup-node@v1
        name: Setup node
        with:
          node-version: "16"
      - run: npm install -g cspell
        name: Install cSpell
      - run: cspell --config ./cSpell.json **/*.md" --no-progress # Update for path to the markdown files
        name: Run cSpell
